### ISSUE TITLE
Issue with the subglyph hack when font missing characters

### ISSUE THREAD

**Issue by weichx** [DanielHerchenbach/sdf_atlas#1]
I've been using this branch in my Unity port of the atlas generation and its been working really well for me. I noticed however that the hack:
````
    // hack: explicit handling of subglyphs completely contained in another subglyph
    const bool isSubglyphEnclosed = (
        font->glyph_map.at(169) == glyph_index ||
        font->glyph_map.at(174) == glyph_index ||
        font->glyph_map.at(8471) == glyph_index ||
        font->glyph_map.at(48) == glyph_index
    );
````
throws exceptions if the font doesn't have a glyph. For example, with Roboto-Regular.ttf I had to completely remove this block to get into a good state. I rarely use cpp and I'm not sure what the right fix is with the glyph_map here, maybe a contains check before the at() call would fix this?

**Comment by DanielHerchenbach** [comment]
Sorry that I didn't see this issue before.
Although you are right here I won't fix this problem because the hack is not needed anymore.
All bugs I found are already fixed on the main branch, in particular (related to this hack):
[https://github.com/astiopin/sdf_atlas/issues/9](url)

**Comment by weichx** [comment]
Thanks for the update 👍
